@startuml actors
rectangle "[[index.html Moped]]" as Moped

rectangle "Krankenhaus" as KH
rectangle "Sozialversicherung" as SV
rectangle "Landesgesundheitsfonds" as LGF
rectangle "Bundesministerium für Soziales, \nGesundheit, Pflege \nund Konsumentenschutz" as BMSGPK


KH -r--> Moped : "[[OperationDefinition-MOPED.Patient.Aufnehmen.html $aufnehmen]]"
KH -r--> Moped : "[[OperationDefinition-MOPED.CoverageEligibilityRequest.Anfragen.html $anfragen]]"
KH -r--> Moped : "[[OperationDefinition-MOPED.Encounter.erfassen.html $entlassen]]"
KH -r--> Moped : "[[test.html $einmelden]]"
KH -r--> Moped : "[[OperationDefinition-MOPED.Encounter.Abrechnen.html $abrechnen]]"
Moped -l--> KH : "[[StructureDefinition-MOPEDCoverageEligibilityResponse.html CoverageEligibilityResponse]]"
Moped -l--> KH : "[[StructureDefinition-MOPEDClaimResponse.html ClaimResponse]]"

SV -u--> Moped : "[[StructureDefinition-MOPEDCoverageEligibilityResponse.html Coverage\nEligibility\nResponse]]"
Moped -d--> SV : "[[StructureDefinition-MOPEDCoverageEligibilityRequest.html Coverage\nEligibility\nRequest]]"
Moped -d--> SV : "[[StructureDefinition-MOPEDClaimResponse.html ClaimResponse]]"

Moped -u--> LGF : "[[StructureDefinition-MOPEDClaim.html Claim]]"
LGF -d--> Moped : "[[OperationDefinition-MOPED.ClaimResponse.Freigeben.html $freigeben]]"
LGF -d--> Moped : "[[OperationDefinition-MOPED.ClaimResponse.Auffordern.html $auffordern]]"

Moped -r--> BMSGPK : "[[StructureDefinition-MOPEDClaimResponse.html ClaimResponse]]"

@enduml