@startuml
skinparam borderColor #000000
skinparam backgroundColor #f5f5f5
skinparam shadowing false
skinparam roundCorner 10
skinparam defaultFontName "Arial"
skinparam defaultFontSize 14
skinparam defaultFontColor #000000

skinparam note {
  BackgroundColor #e0e5f0-#d1d9e6
  BorderColor #8b95a5
  BorderThickness 1
  RoundCorner 8
  Padding 6
  FontColor #111827
  Shadowing true
}

skinparam HyperlinkColor #0000EE
skinparam HyperlinkUnderline false

skinparam sequence {
  ParticipantBorderColor #555555
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
  ParticipantFontSize 14
  ParticipantPadding 20
  ArrowColor #111827
  ArrowThickness 2
  ArrowFontColor #000000
  ArrowFontSize 13
  GroupBorderColor #111827
  GroupBackgroundColor #f3f4f6
  GroupBorderThickness 1
}

skinparam BoxPadding 20
skinparam BoxBorderColor #555555

box "\n  KH (Herz Jesu Krankenhaus)  " #f5e599
  actor KH as "KH"
end box

box "\n       Moped       " #c5f7ba
  participant MP as "Moped"
end box

box "\n    SV (ÖGK,...)    " #bac4f7
  actor SV as "SV (ÖGK)"
end box

box "\n LGF (Landesgesundheitsfonds)  " #f7d0ba
  actor LGF as "LGF (Landesgesundheitsfonds)"
end box

box "\n        Bund        " #fcb3b3
  actor Bund as "Bund"
end box


KH->> MP:<b>1</b> $aufnehmen
Note over KH: Patientin Amanda Ambulant wird%n() in die Unfallambulanz aufgenommen %n()und die ÖGK Wien als zuständige%n() Versicherung gesetzt
KH->>MP:<b>2</b> $anfragen
Note over KH: Anfrage auf Versicherungsanspruchserklärung
SV->>MP:<b>3a</b> GET ClaimResponse?status=active %n() &use=preauthorization
Note over SV: alle offenen VAEs abfragen%n()und intern bearbeiten
SV->>MP:<b>3b</b> $antworten (Status 00)
Note over SV: Fallübernahme bestätigt%n()(Status 00) 
KH->>MP:<b>4a</b> GET Composition?id={id}
Note over KH: aktuellen Stand des Falls abfragen%n()(inkl. bestätigte VAE)
KH->>MP:<b>4b</b> $update
Note over KH: Kontakt mit der Abteilung für %n()Radiologie (Röntgen)
KH->>MP:<b>5</b> $update
Note over KH: Diagnose „gebrochenes Schlüsselbein" und %n()eine erbrachte Leistung werden erfasst 
KH->>MP:<b>6</b> $update
Note over KH: Restliche Falldaten für Amanda Ambulant %n() werden ergänzt
loop $abrechnen / $entscheiden (vorläufig)
    KH->>MP:<b>7</b> $abrechnen 
    Note over KH: Abrechnung aller Leistungen eingereicht
    LGF->>MP:<b>8a</b> GET ClaimResponse?status=active&use=claim
    Note over LGF: offene Abrechnungen abfragen%n()und intern bearbeiten
    LGF->>MP:<b>8b</b> $entscheiden
    Note over LGF: Alle Posten genehmigt%n()(keine Änderungen)
end
KH->>MP:<b>9a</b> GET Composition?id={id}
Note over KH: aktuellen Stand des Falls abfragen%n()(inkl. bestätigte Abrechnung)
KH->>MP:<b>9b</b>  final $abrechnen 
Note over KH: Finale Abrechnung seitens des KH
LGF->>MP:<b>10a</b> GET ClaimResponse?status=active&use=claim&_endgueltig=true
Note over LGF: offene Abrechnungen abfragen%n()und intern bearbeiten
LGF->>MP:<b>10b</b> final $entscheiden
Note over LGF: Endgültige Entscheidung %n()zur Abrechnung 
Note over LGF: Kosteninformationen werden %n()im Datensatz ergänzt 
SV->>MP:<b>11</b> GET LKFResponse?_endgueltig=true
Note over SV: Kosteninformation abrufen
Bund->>MP:<b>12</b>  GET Composition?status=final
Note over Bund: Zugriff auf finale Composition 


Note over MP: Fall für Moped abgeschlossen

@enduml