@startuml
skinparam borderColor #000000
skinparam backgroundColor #f5f5f5
skinparam shadowing false
skinparam roundCorner 10
skinparam defaultFontName "Arial"
skinparam defaultFontSize 14
skinparam defaultFontColor #000000

skinparam note {
  BackgroundColor #e0e5f0-#d1d9e6
  BorderColor #8b95a5
  BorderThickness 1
  RoundCorner 8
  Padding 6
  FontColor #111827
  Shadowing true
}

skinparam HyperlinkColor #0000EE
skinparam HyperlinkUnderline false

skinparam sequence {
  ParticipantBorderColor #555555
  ParticipantBackgroundColor #ffffff
  ParticipantFontColor #000000
  ParticipantFontSize 14
  ParticipantPadding 20
  ArrowColor #111827
  ArrowThickness 2
  ArrowFontColor #000000
  ArrowFontSize 13
  GroupBorderColor #111827
  GroupBackgroundColor #f3f4f6
  GroupBorderThickness 1
}

skinparam BoxPadding 20
skinparam BoxBorderColor #555555

box "\n  KH (Herz Jesu Krankenhaus)  " #f5e599
  actor KH as "KH"
end box

box "\n       Moped       " #c5f7ba
  participant MP as "Moped"
end box

box "\n    SV (ÖGK,...)    " #c0c0c0
  actor SV as "SV (ÖGK)"
end box

box "\n LGF (Landesgesundheitsfonds)  " #f7d0ba
  actor LGF as "LGF (Landesgesundheitsfonds)"
end box

box "\n        Bund        " #fcb3b3
  actor Bund as "Bund"
end box

KH->> MP:<b>1</b> [[OperationDefinition-MOPED.Patient.Aufnehmen.html $aufnehmen]]
note over KH: Sven Selbstzahler wird stationär aufgenommen,%n() eine Selbstzahler-Coverage erfasst %n()und keine zuständige Versicherung gesetzt

KH->>MP:<b>2</b> [[OperationDefinition-MOPED.Daten.Update.html $update]]
Note over KH: Verlegung auf Abteilung Innere Medizin

KH->>MP:<b>3</b> [[OperationDefinition-MOPED.Daten.Update.html $update]]
Note over KH: Diagnose "Herzinsuffizienz" und Leistung "EKG" erfasst

KH->>MP:<b>4</b> [[OperationDefinition-MOPED.Patient.Entlassen.html $entlassen]]
note over KH: Sven Selbstzahler wird entlassen


loop [[OperationDefinition-MOPED.Encounter.Abrechnen.html $abrechnen]] / [[OperationDefinition-MOPED.Abrechnung.Genehmigen.html $genehmigen]] (vorläufig)
    KH->>MP:<b>5</b> [[OperationDefinition-MOPED.Encounter.Abrechnen.html $abrechnen]] 
    Note over KH: Abrechnung aller Leistungen eingereicht
    LGF->>MP:<b>6a</b> GET Claim?status=active&use=claim%n()&_has:ClaimResponse:request:status:not=active
    Note over LGF: unbeantwortete Abrechnungen abfragen%n()und intern bearbeiten
    LGF->>MP:<b>6b</b> [[OperationDefinition-MOPED.Abrechnung.Genehmigen.html $genehmigen]]
    Note over LGF: Alle Posten genehmigt%n()(keine Änderungen)
end
KH->>MP:<b>7a</b> GET Composition?id={id}
Note over KH: aktuellen Stand des Falls abfragen%n()(inkl. bestätigte Abrechnung)
KH->>MP:<b>7b</b>  final [[OperationDefinition-MOPED.Encounter.Abrechnen.html $abrechnen]] 
Note over KH: Finale Abrechnung seitens des KH
LGF->>MP:<b>8a</b> GET Claim?status=active&use=claim&final=true%n()&_has:ClaimResponse:request:status:not=active
Note over LGF: unbeantwortete Abrechnungen abfragen%n()und intern bearbeiten
LGF->>MP:<b>8b</b> final [[OperationDefinition-MOPED.Abrechnung.Genehmigen.html $genehmigen]]
Note over LGF: Endgültige Entscheidung %n()zur Abrechnung 
Bund->>MP:<b>9</b>  GET Composition?status=final
Note over Bund: Zugriff auf finale Composition

Note over MP: Fall für Moped abgeschlossen

@enduml